INSERT INTO `language` VALUES(1, 'English', 'en');
INSERT INTO `language` VALUES(2, 'Afar', 'aa');
INSERT INTO `language` VALUES(3, 'Abkhazian', 'ab');
INSERT INTO `language` VALUES(4, 'Afrikaans', 'af');
INSERT INTO `language` VALUES(5, 'Amharic', 'am');
INSERT INTO `language` VALUES(6, 'Arabic', 'ar');
INSERT INTO `language` VALUES(7, 'Assamese', 'as');
INSERT INTO `language` VALUES(8, 'Aymara', 'ay');
INSERT INTO `language` VALUES(9, 'Azerbaijani', 'az');
INSERT INTO `language` VALUES(10, 'Bashkir', 'ba');
INSERT INTO `language` VALUES(11, 'Belarusian', 'be');
INSERT INTO `language` VALUES(12, 'Bulgarian', 'bg');
INSERT INTO `language` VALUES(13, 'Bihari', 'bh');
INSERT INTO `language` VALUES(14, 'Bislama', 'bi');
INSERT INTO `language` VALUES(15, 'Bengali/Bangla', 'bn');
INSERT INTO `language` VALUES(16, 'Tibetan', 'bo');
INSERT INTO `language` VALUES(17, 'Breton', 'br');
INSERT INTO `language` VALUES(18, 'Catalan', 'ca');
INSERT INTO `language` VALUES(19, 'Corsican', 'co');
INSERT INTO `language` VALUES(20, 'Czech', 'cs');
INSERT INTO `language` VALUES(21, 'Welsh', 'cy');
INSERT INTO `language` VALUES(22, 'Danish', 'da');
INSERT INTO `language` VALUES(23, 'German', 'de');
INSERT INTO `language` VALUES(24, 'Bhutani', 'dz');
INSERT INTO `language` VALUES(25, 'Greek', 'el');
INSERT INTO `language` VALUES(26, 'Esperanto', 'eo');
INSERT INTO `language` VALUES(27, 'Spanish', 'es');
INSERT INTO `language` VALUES(28, 'Estonian', 'et');
INSERT INTO `language` VALUES(29, 'Basque', 'eu');
INSERT INTO `language` VALUES(30, 'Persian', 'fa');
INSERT INTO `language` VALUES(31, 'Finnish', 'fi');
INSERT INTO `language` VALUES(32, 'Fiji', 'fj');
INSERT INTO `language` VALUES(33, 'Faeroese', 'fo');
INSERT INTO `language` VALUES(34, 'French', 'fr');
INSERT INTO `language` VALUES(35, 'Frisian', 'fy');
INSERT INTO `language` VALUES(36, 'Irish', 'ga');
INSERT INTO `language` VALUES(37, 'Scots/Gaelic', 'gd');
INSERT INTO `language` VALUES(38, 'Galician', 'gl');
INSERT INTO `language` VALUES(39, 'Guarani', 'gn');
INSERT INTO `language` VALUES(40, 'Gujarati', 'gu');
INSERT INTO `language` VALUES(41, 'Hausa', 'ha');
INSERT INTO `language` VALUES(42, 'Hindi', 'hi');
INSERT INTO `language` VALUES(43, 'Croatian', 'hr');
INSERT INTO `language` VALUES(44, 'Hungarian', 'hu');
INSERT INTO `language` VALUES(45, 'Armenian', 'hy');
INSERT INTO `language` VALUES(46, 'Interlingua', 'ia');
INSERT INTO `language` VALUES(47, 'Interlingue', 'ie');
INSERT INTO `language` VALUES(48, 'Inupiak', 'ik');
INSERT INTO `language` VALUES(49, 'Indonesian', 'in');
INSERT INTO `language` VALUES(50, 'Icelandic', 'is');
INSERT INTO `language` VALUES(51, 'Italian', 'it');
INSERT INTO `language` VALUES(52, 'Hebrew', 'iw');
INSERT INTO `language` VALUES(53, 'Japanese', 'ja');
INSERT INTO `language` VALUES(54, 'Yiddish', 'ji');
INSERT INTO `language` VALUES(55, 'Javanese', 'jw');
INSERT INTO `language` VALUES(56, 'Georgian', 'ka');
INSERT INTO `language` VALUES(57, 'Kazakh', 'kk');
INSERT INTO `language` VALUES(58, 'Greenlandic', 'kl');
INSERT INTO `language` VALUES(59, 'Cambodian', 'km');
INSERT INTO `language` VALUES(60, 'Kannada', 'kn');
INSERT INTO `language` VALUES(61, 'Korean', 'ko');
INSERT INTO `language` VALUES(62, 'Kashmiri', 'ks');
INSERT INTO `language` VALUES(63, 'Kurdish', 'ku');
INSERT INTO `language` VALUES(64, 'Kirghiz', 'ky');
INSERT INTO `language` VALUES(65, 'Latin', 'la');
INSERT INTO `language` VALUES(66, 'Lingala', 'ln');
INSERT INTO `language` VALUES(67, 'Laothian', 'lo');
INSERT INTO `language` VALUES(68, 'Lithuanian', 'lt');
INSERT INTO `language` VALUES(69, 'Latvian/Lettish', 'lv');
INSERT INTO `language` VALUES(70, 'Malagasy', 'mg');
INSERT INTO `language` VALUES(71, 'Maori', 'mi');
INSERT INTO `language` VALUES(72, 'Macedonian', 'mk');
INSERT INTO `language` VALUES(73, 'Malayalam', 'ml');
INSERT INTO `language` VALUES(74, 'Mongolian', 'mn');
INSERT INTO `language` VALUES(75, 'Moldavian', 'mo');
INSERT INTO `language` VALUES(76, 'Marathi', 'mr');
INSERT INTO `language` VALUES(77, 'Malay', 'ms');
INSERT INTO `language` VALUES(78, 'Maltese', 'mt');
INSERT INTO `language` VALUES(79, 'Burmese', 'my');
INSERT INTO `language` VALUES(80, 'Nauru', 'na');
INSERT INTO `language` VALUES(81, 'Nepali', 'ne');
INSERT INTO `language` VALUES(82, 'Dutch', 'nl');
INSERT INTO `language` VALUES(83, 'Norwegian', 'no');
INSERT INTO `language` VALUES(84, 'Occitan', 'oc');
INSERT INTO `language` VALUES(85, '(Afan)/Oromoor/Oriya', 'om');
INSERT INTO `language` VALUES(86, 'Punjabi', 'pa');
INSERT INTO `language` VALUES(87, 'Polish', 'pl');
INSERT INTO `language` VALUES(88, 'Pashto/Pushto', 'ps');
INSERT INTO `language` VALUES(89, 'Portuguese', 'pt');
INSERT INTO `language` VALUES(90, 'Quechua', 'qu');
INSERT INTO `language` VALUES(91, 'Rhaeto-Romance', 'rm');
INSERT INTO `language` VALUES(92, 'Kirundi', 'rn');
INSERT INTO `language` VALUES(93, 'Romanian', 'ro');
INSERT INTO `language` VALUES(94, 'Russian', 'ru');
INSERT INTO `language` VALUES(95, 'Kinyarwanda', 'rw');
INSERT INTO `language` VALUES(96, 'Sanskrit', 'sa');
INSERT INTO `language` VALUES(97, 'Sindhi', 'sd');
INSERT INTO `language` VALUES(98, 'Sangro', 'sg');
INSERT INTO `language` VALUES(99, 'Serbo-Croatian', 'sh');
INSERT INTO `language` VALUES(100, 'Singhalese', 'si');
INSERT INTO `language` VALUES(101, 'Slovak', 'sk');
INSERT INTO `language` VALUES(102, 'Slovenian', 'sl');
INSERT INTO `language` VALUES(103, 'Samoan', 'sm');
INSERT INTO `language` VALUES(104, 'Shona', 'sn');
INSERT INTO `language` VALUES(105, 'Somali', 'so');
INSERT INTO `language` VALUES(106, 'Albanian', 'sq');
INSERT INTO `language` VALUES(107, 'Serbian', 'sr');
INSERT INTO `language` VALUES(108, 'Siswati', 'ss');
INSERT INTO `language` VALUES(109, 'Sesotho', 'st');
INSERT INTO `language` VALUES(110, 'Sundanese', 'su');
INSERT INTO `language` VALUES(111, 'Swedish', 'sv');
INSERT INTO `language` VALUES(112, 'Swahili', 'sw');
INSERT INTO `language` VALUES(113, 'Tamil', 'ta');
INSERT INTO `language` VALUES(114, 'Telugu', 'te');
INSERT INTO `language` VALUES(115, 'Tajik', 'tg');
INSERT INTO `language` VALUES(116, 'Thai', 'th');
INSERT INTO `language` VALUES(117, 'Tigrinya', 'ti');
INSERT INTO `language` VALUES(118, 'Turkmen', 'tk');
INSERT INTO `language` VALUES(119, 'Tagalog', 'tl');
INSERT INTO `language` VALUES(120, 'Setswana', 'tn');
INSERT INTO `language` VALUES(121, 'Tonga', 'to');
INSERT INTO `language` VALUES(122, 'Turkish', 'tr');
INSERT INTO `language` VALUES(123, 'Tsonga', 'ts');
INSERT INTO `language` VALUES(124, 'Tatar', 'tt');
INSERT INTO `language` VALUES(125, 'Twi', 'tw');
INSERT INTO `language` VALUES(126, 'Ukrainian', 'uk');
INSERT INTO `language` VALUES(127, 'Urdu', 'ur');
INSERT INTO `language` VALUES(128, 'Uzbek', 'uz');
INSERT INTO `language` VALUES(129, 'Vietnamese', 'vi');
INSERT INTO `language` VALUES(130, 'Volapuk', 'vo');
INSERT INTO `language` VALUES(131, 'Wolof', 'wo');
INSERT INTO `language` VALUES(132, 'Xhosa', 'xh');
INSERT INTO `language` VALUES(133, 'Yoruba', 'yo');
INSERT INTO `language` VALUES(134, 'Chinese', 'zh');
INSERT INTO `language` VALUES(135, 'Zulu', 'zu');

INSERT INTO country (name, flagcode, code) VALUES ('Afghanistan', 'AF', 'AFG');
INSERT INTO country (name, flagcode, code) VALUES ('Åland Islands', 'AX', 'ALA');
INSERT INTO country (name, flagcode, code) VALUES ('Albania', 'AL', 'ALB');
INSERT INTO country (name, flagcode, code) VALUES ('Algeria', 'DZ', 'DZA');
INSERT INTO country (name, flagcode, code) VALUES ('American Samoa', 'AS', 'ASM');
INSERT INTO country (name, flagcode, code) VALUES ('Andorra', 'AD', 'AND');
INSERT INTO country (name, flagcode, code) VALUES ('Angola', 'AO', 'AGO');
INSERT INTO country (name, flagcode, code) VALUES ('Anguilla', 'AI', 'AIA');
INSERT INTO country (name, flagcode, code) VALUES ('Antarctica', 'AQ', 'ATA');
INSERT INTO country (name, flagcode, code) VALUES ('Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO country (name, flagcode, code) VALUES ('Argentina', 'AR', 'ARG');
INSERT INTO country (name, flagcode, code) VALUES ('Armenia', 'AM', 'ARM');
INSERT INTO country (name, flagcode, code) VALUES ('Aruba', 'AW', 'ABW');
INSERT INTO country (name, flagcode, code) VALUES ('Australia', 'AU', 'AUS');
INSERT INTO country (name, flagcode, code) VALUES ('Austria', 'AT', 'AUT');
INSERT INTO country (name, flagcode, code) VALUES ('Azerbaijan', 'AZ', 'AZE');
INSERT INTO country (name, flagcode, code) VALUES ('Bahamas', 'BS', 'BHS');
INSERT INTO country (name, flagcode, code) VALUES ('Bahrain', 'BH', 'BHR');
INSERT INTO country (name, flagcode, code) VALUES ('Bangladesh', 'BD', 'BGD');
INSERT INTO country (name, flagcode, code) VALUES ('Barbados', 'BB', 'BRB');
INSERT INTO country (name, flagcode, code) VALUES ('Belarus', 'BY', 'BLR');
INSERT INTO country (name, flagcode, code) VALUES ('Belgium', 'BE', 'BEL');
INSERT INTO country (name, flagcode, code) VALUES ('Belize', 'BZ', 'BLZ');
INSERT INTO country (name, flagcode, code) VALUES ('Benin', 'BJ', 'BEN');
INSERT INTO country (name, flagcode, code) VALUES ('Bermuda', 'BM', 'BMU');
INSERT INTO country (name, flagcode, code) VALUES ('Bhutan', 'BT', 'BTN');
INSERT INTO country (name, flagcode, code) VALUES ('Bolivia', 'BO', 'BOL');
INSERT INTO country (name, flagcode, code) VALUES ('Bonaire, Saint Eustatius and Saba (Netherlands)', 'BQ', 'BES');
INSERT INTO country (name, flagcode, code) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO country (name, flagcode, code) VALUES ('Botswana', 'BW', 'BWA');
INSERT INTO country (name, flagcode, code) VALUES ('Bouvet Island', 'BV', 'BVT');
INSERT INTO country (name, flagcode, code) VALUES ('Brazil', 'BR', 'BRA');
INSERT INTO country (name, flagcode, code) VALUES ('British Indian Ocean Territory', 'IO', 'IOT');
INSERT INTO country (name, flagcode, code) VALUES ('Brunei Darussalam', 'BN', 'BRN');
INSERT INTO country (name, flagcode, code) VALUES ('Bulgaria', 'BG', 'BGR');
INSERT INTO country (name, flagcode, code) VALUES ('Burkina Faso', 'BF', 'BFA');
INSERT INTO country (name, flagcode, code) VALUES ('Burundi', 'BI', 'BDI');
INSERT INTO country (name, flagcode, code) VALUES ('Cambodia', 'KH', 'KHM');
INSERT INTO country (name, flagcode, code) VALUES ('Cameroon', 'CM', 'CMR');
INSERT INTO country (name, flagcode, code) VALUES ('Canada', 'CA', 'CAN');
INSERT INTO country (name, flagcode, code) VALUES ('Cape Verde', 'CV', 'CPV');
INSERT INTO country (name, flagcode, code) VALUES ('Cayman Islands', 'KY', 'CYM');
INSERT INTO country (name, flagcode, code) VALUES ('Central African Republic', 'CF', 'CAF');
INSERT INTO country (name, flagcode, code) VALUES ('Chad', 'TD', 'TCD');
INSERT INTO country (name, flagcode, code) VALUES ('Chile', 'CL', 'CHL');
INSERT INTO country (name, flagcode, code) VALUES ('China', 'CN', 'CHN');
INSERT INTO country (name, flagcode, code) VALUES ('Christmas Island', 'CX', 'CXR');
INSERT INTO country (name, flagcode, code) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK');
INSERT INTO country (name, flagcode, code) VALUES ('Colombia', 'CO', 'COL');
INSERT INTO country (name, flagcode, code) VALUES ('Comoros', 'KM', 'COM');
INSERT INTO country (name, flagcode, code) VALUES ('Congo', 'CG', 'COG');
INSERT INTO country (name, flagcode, code) VALUES ('Congo-Kinshasa', 'CD', 'COD');
INSERT INTO country (name, flagcode, code) VALUES ('Cook Islands', 'CK', 'COK');
INSERT INTO country (name, flagcode, code) VALUES ('Costa Rica', 'CR', 'CRI');
INSERT INTO country (name, flagcode, code) VALUES ('Ivory Coast', 'CI', 'CIV');
INSERT INTO country (name, flagcode, code) VALUES ('Croatia', 'HR', 'HRV');
INSERT INTO country (name, flagcode, code) VALUES ('Cuba', 'CU', 'CUB');
INSERT INTO country (name, flagcode, code) VALUES ('Curaçao', 'CW', 'CUW');
INSERT INTO country (name, flagcode, code) VALUES ('Cyprus', 'CY', 'CYP');
INSERT INTO country (name, flagcode, code) VALUES ('Czech Republic', 'CZ', 'CZE');
INSERT INTO country (name, flagcode, code) VALUES ('Denmark', 'DK', 'DNK');
INSERT INTO country (name, flagcode, code) VALUES ('Djibouti', 'DJ', 'DJI');
INSERT INTO country (name, flagcode, code) VALUES ('Dominica', 'DM', 'DMA');
INSERT INTO country (name, flagcode, code) VALUES ('Dominican Republic', 'DO', 'DOM');
INSERT INTO country (name, flagcode, code) VALUES ('Ecuador', 'EC', 'ECU');
INSERT INTO country (name, flagcode, code) VALUES ('Egypt', 'EG', 'EGY');
INSERT INTO country (name, flagcode, code) VALUES ('El Salvador', 'SV', 'SLV');
INSERT INTO country (name, flagcode, code) VALUES ('Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO country (name, flagcode, code) VALUES ('Eritrea', 'ER', 'ERI');
INSERT INTO country (name, flagcode, code) VALUES ('Estonia', 'EE', 'EST');
INSERT INTO country (name, flagcode, code) VALUES ('Ethiopia', 'ET', 'ETH');
INSERT INTO country (name, flagcode, code) VALUES ('Falkland Islands (Malvinas)', 'FK', 'FLK');
INSERT INTO country (name, flagcode, code) VALUES ('Faroe Islands', 'FO', 'FRO');
INSERT INTO country (name, flagcode, code) VALUES ('Fiji', 'FJ', 'FJI');
INSERT INTO country (name, flagcode, code) VALUES ('Finland', 'FI', 'FIN');
INSERT INTO country (name, flagcode, code) VALUES ('France', 'FR', 'FRA');
INSERT INTO country (name, flagcode, code) VALUES ('French Guiana', 'GF', 'GUF');
INSERT INTO country (name, flagcode, code) VALUES ('French Polynesia', 'PF', 'PYF');
INSERT INTO country (name, flagcode, code) VALUES ('French Southern Territories', 'TF', 'ATF');
INSERT INTO country (name, flagcode, code) VALUES ('Gabon', 'GA', 'GAB');
INSERT INTO country (name, flagcode, code) VALUES ('Gambia', 'GM', 'GMB');
INSERT INTO country (name, flagcode, code) VALUES ('Georgia', 'GE', 'GEO');
INSERT INTO country (name, flagcode, code) VALUES ('Germany', 'DE', 'DEU');
INSERT INTO country (name, flagcode, code) VALUES ('Ghana', 'GH', 'GHA');
INSERT INTO country (name, flagcode, code) VALUES ('Gibraltar', 'GI', 'GIB');
INSERT INTO country (name, flagcode, code) VALUES ('Greece', 'GR', 'GRC');
INSERT INTO country (name, flagcode, code) VALUES ('Greenland', 'GL', 'GRL');
INSERT INTO country (name, flagcode, code) VALUES ('Grenada', 'GD', 'GRD');
INSERT INTO country (name, flagcode, code) VALUES ('Guadeloupe', 'GP', 'GLP');
INSERT INTO country (name, flagcode, code) VALUES ('Guam', 'GU', 'GUM');
INSERT INTO country (name, flagcode, code) VALUES ('Guatemala', 'GT', 'GTM');
INSERT INTO country (name, flagcode, code) VALUES ('Guernsey', 'GG', 'GGY');
INSERT INTO country (name, flagcode, code) VALUES ('Guinea', 'GN', 'GIN');
INSERT INTO country (name, flagcode, code) VALUES ('Guinea-Bissau', 'GW', 'GNB');
INSERT INTO country (name, flagcode, code) VALUES ('Guyana', 'GY', 'GUY');
INSERT INTO country (name, flagcode, code) VALUES ('Haiti', 'HT', 'HTI');
INSERT INTO country (name, flagcode, code) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD');
INSERT INTO country (name, flagcode, code) VALUES ('Vatican City', 'VA', 'VAT');
INSERT INTO country (name, flagcode, code) VALUES ('Honduras', 'HN', 'HND');
INSERT INTO country (name, flagcode, code) VALUES ('Hong Kong', 'HK', 'HKG');
INSERT INTO country (name, flagcode, code) VALUES ('Hungary', 'HU', 'HUN');
INSERT INTO country (name, flagcode, code) VALUES ('Iceland', 'IS', 'ISL');
INSERT INTO country (name, flagcode, code) VALUES ('India', 'IN', 'IND');
INSERT INTO country (name, flagcode, code) VALUES ('Indonesia', 'ID', 'IDN');
INSERT INTO country (name, flagcode, code) VALUES ('Iran', 'IR', 'IRN');
INSERT INTO country (name, flagcode, code) VALUES ('Iraq', 'IQ', 'IRQ');
INSERT INTO country (name, flagcode, code) VALUES ('Ireland', 'IE', 'IRL');
INSERT INTO country (name, flagcode, code) VALUES ('Isle of Man', 'IM', 'IMN');
INSERT INTO country (name, flagcode, code) VALUES ('Israel', 'IL', 'ISR');
INSERT INTO country (name, flagcode, code) VALUES ('Italy', 'IT', 'ITA');
INSERT INTO country (name, flagcode, code) VALUES ('Jamaica', 'JM', 'JAM');
INSERT INTO country (name, flagcode, code) VALUES ('Japan', 'JP', 'JPN');
INSERT INTO country (name, flagcode, code) VALUES ('Jersey', 'JE', 'JEY');
INSERT INTO country (name, flagcode, code) VALUES ('Jordan', 'JO', 'JOR');
INSERT INTO country (name, flagcode, code) VALUES ('Kazakhstan', 'KZ', 'KAZ');
INSERT INTO country (name, flagcode, code) VALUES ('Kenya', 'KE', 'KEN');
INSERT INTO country (name, flagcode, code) VALUES ('Kiribati', 'KI', 'KIR');
INSERT INTO country (name, flagcode, code) VALUES ('North Korea', 'KP', 'PRK');
INSERT INTO country (name, flagcode, code) VALUES ('South Korea', 'KR', 'KOR');
INSERT INTO country (name, flagcode, code) VALUES ('Kuwait', 'KW', 'KWT');
INSERT INTO country (name, flagcode, code) VALUES ('Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO country (name, flagcode, code) VALUES ('Laos', 'LA', 'LAO');
INSERT INTO country (name, flagcode, code) VALUES ('Latvia', 'LV', 'LVA');
INSERT INTO country (name, flagcode, code) VALUES ('Lebanon', 'LB', 'LBN');
INSERT INTO country (name, flagcode, code) VALUES ('Lesotho', 'LS', 'LSO');
INSERT INTO country (name, flagcode, code) VALUES ('Liberia', 'LR', 'LBR');
INSERT INTO country (name, flagcode, code) VALUES ('Libyan Arab Jamahiriya', 'LY', 'LBY');
INSERT INTO country (name, flagcode, code) VALUES ('Liechtenstein', 'LI', 'LIE');
INSERT INTO country (name, flagcode, code) VALUES ('Lithuania', 'LT', 'LTU');
INSERT INTO country (name, flagcode, code) VALUES ('Luxembourg', 'LU', 'LUX');
INSERT INTO country (name, flagcode, code) VALUES ('Macao', 'MO', 'MAC');
INSERT INTO country (name, flagcode, code) VALUES ('North Macedonia', 'MK', 'MKD');
INSERT INTO country (name, flagcode, code) VALUES ('Madagascar', 'MG', 'MDG');
INSERT INTO country (name, flagcode, code) VALUES ('Malawi', 'MW', 'MWI');
INSERT INTO country (name, flagcode, code) VALUES ('Malaysia', 'MY', 'MYS');
INSERT INTO country (name, flagcode, code) VALUES ('Maldives', 'MV', 'MDV');
INSERT INTO country (name, flagcode, code) VALUES ('Mali', 'ML', 'MLI');
INSERT INTO country (name, flagcode, code) VALUES ('Malta', 'MT', 'MLT');
INSERT INTO country (name, flagcode, code) VALUES ('Marshall Islands', 'MH', 'MHL');
INSERT INTO country (name, flagcode, code) VALUES ('Martinique', 'MQ', 'MTQ');
INSERT INTO country (name, flagcode, code) VALUES ('Mauritania', 'MR', 'MRT');
INSERT INTO country (name, flagcode, code) VALUES ('Mauritius', 'MU', 'MUS');
INSERT INTO country (name, flagcode, code) VALUES ('Mayotte', 'YT', 'MYT');
INSERT INTO country (name, flagcode, code) VALUES ('Mexico', 'MX', 'MEX');
INSERT INTO country (name, flagcode, code) VALUES ('Micronesia, Federated States of', 'FM', 'FSM');
INSERT INTO country (name, flagcode, code) VALUES ('Moldova, Republic of', 'MD', 'MDA');
INSERT INTO country (name, flagcode, code) VALUES ('Monaco', 'MC', 'MCO');
INSERT INTO country (name, flagcode, code) VALUES ('Mongolia', 'MN', 'MNG');
INSERT INTO country (name, flagcode, code) VALUES ('Montenegro', 'ME', 'MNE');
INSERT INTO country (name, flagcode, code) VALUES ('Montserrat', 'MS', 'MSR');
INSERT INTO country (name, flagcode, code) VALUES ('Morocco', 'MA', 'MAR');
INSERT INTO country (name, flagcode, code) VALUES ('Mozambique', 'MZ', 'MOZ');
INSERT INTO country (name, flagcode, code) VALUES ('Myanmar', 'MM', 'MMR');
INSERT INTO country (name, flagcode, code) VALUES ('Namibia', 'NA', 'NAM');
INSERT INTO country (name, flagcode, code) VALUES ('Nauru', 'NR', 'NRU');
INSERT INTO country (name, flagcode, code) VALUES ('Nepal', 'NP', 'NPL');
INSERT INTO country (name, flagcode, code) VALUES ('Netherlands', 'NL', 'NLD');
INSERT INTO country (name, flagcode, code) VALUES ('New Caledonia', 'NC', 'NCL');
INSERT INTO country (name, flagcode, code) VALUES ('New Zealand', 'NZ', 'NZL');
INSERT INTO country (name, flagcode, code) VALUES ('Nicaragua', 'NI', 'NIC');
INSERT INTO country (name, flagcode, code) VALUES ('Niger', 'NE', 'NER');
INSERT INTO country (name, flagcode, code) VALUES ('Nigeria', 'NG', 'NGA');
INSERT INTO country (name, flagcode, code) VALUES ('Niue', 'NU', 'NIU');
INSERT INTO country (name, flagcode, code) VALUES ('Norfolk Island', 'NF', 'NFK');
INSERT INTO country (name, flagcode, code) VALUES ('Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO country (name, flagcode, code) VALUES ('Norway', 'NO', 'NOR');
INSERT INTO country (name, flagcode, code) VALUES ('Oman', 'OM', 'OMN');
INSERT INTO country (name, flagcode, code) VALUES ('Pakistan', 'PK', 'PAK');
INSERT INTO country (name, flagcode, code) VALUES ('Palau', 'PW', 'PLW');
INSERT INTO country (name, flagcode, code) VALUES ('Palestinian Territory, Occupied', 'PS', 'PSE');
INSERT INTO country (name, flagcode, code) VALUES ('Panama', 'PA', 'PAN');
INSERT INTO country (name, flagcode, code) VALUES ('Papua New Guinea', 'PG', 'PNG');
INSERT INTO country (name, flagcode, code) VALUES ('Paraguay', 'PY', 'PRY');
INSERT INTO country (name, flagcode, code) VALUES ('Peru', 'PE', 'PER');
INSERT INTO country (name, flagcode, code) VALUES ('Philippines', 'PH', 'PHL');
INSERT INTO country (name, flagcode, code) VALUES ('Pitcairn', 'PN', 'PCN');
INSERT INTO country (name, flagcode, code) VALUES ('Poland', 'PL', 'POL');
INSERT INTO country (name, flagcode, code) VALUES ('Portugal', 'PT', 'PRT');
INSERT INTO country (name, flagcode, code) VALUES ('Puerto Rico', 'PR', 'PRI');
INSERT INTO country (name, flagcode, code) VALUES ('Qatar', 'QA', 'QAT');
INSERT INTO country (name, flagcode, code) VALUES ('Réunion', 'RE', 'REU');
INSERT INTO country (name, flagcode, code) VALUES ('Romania', 'RO', 'ROU');
INSERT INTO country (name, flagcode, code) VALUES ('Russian Federation', 'RU', 'RUS');
INSERT INTO country (name, flagcode, code) VALUES ('Rwanda', 'RW', 'RWA');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Barthélemy', 'BL', 'BLM');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Lucia', 'LC', 'LCA');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Martin (French part)', 'MF', 'MAF');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO country (name, flagcode, code) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO country (name, flagcode, code) VALUES ('Samoa', 'WS', 'WSM');
INSERT INTO country (name, flagcode, code) VALUES ('San Marino', 'SM', 'SMR');
INSERT INTO country (name, flagcode, code) VALUES ('Sao Tome and Principe', 'ST', 'STP');
INSERT INTO country (name, flagcode, code) VALUES ('Saudi Arabia', 'SA', 'SAU');
INSERT INTO country (name, flagcode, code) VALUES ('Senegal', 'SN', 'SEN');
INSERT INTO country (name, flagcode, code) VALUES ('Serbia', 'RS', 'SRB');
INSERT INTO country (name, flagcode, code) VALUES ('Seychelles', 'SC', 'SYC');
INSERT INTO country (name, flagcode, code) VALUES ('Sierra Leone', 'SL', 'SLE');
INSERT INTO country (name, flagcode, code) VALUES ('Singapore', 'SG', 'SGP');
INSERT INTO country (name, flagcode, code) VALUES ('Sint Maarten (Dutch part)', 'SX', 'SXM');
INSERT INTO country (name, flagcode, code) VALUES ('Slovakia', 'SK', 'SVK');
INSERT INTO country (name, flagcode, code) VALUES ('Slovenia', 'SI', 'SVN');
INSERT INTO country (name, flagcode, code) VALUES ('Solomon Islands', 'SB', 'SLB');
INSERT INTO country (name, flagcode, code) VALUES ('Somalia', 'SO', 'SOM');
INSERT INTO country (name, flagcode, code) VALUES ('South Africa', 'ZA', 'ZAF');
INSERT INTO country (name, flagcode, code) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS');
INSERT INTO country (name, flagcode, code) VALUES ('Spain', 'ES', 'ESP');
INSERT INTO country (name, flagcode, code) VALUES ('Sri Lanka', 'LK', 'LKA');
INSERT INTO country (name, flagcode, code) VALUES ('Sudan', 'SD', 'SDN');
INSERT INTO country (name, flagcode, code) VALUES ('Suriname', 'SR', 'SUR');
INSERT INTO country (name, flagcode, code) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM');
INSERT INTO country (name, flagcode, code) VALUES ('Swaziland', 'SZ', 'SWZ');
INSERT INTO country (name, flagcode, code) VALUES ('Sweden', 'SE', 'SWE');
INSERT INTO country (name, flagcode, code) VALUES ('Switzerland', 'CH', 'CHE');
INSERT INTO country (name, flagcode, code) VALUES ('Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO country (name, flagcode, code) VALUES ('Taiwan, Province of China', 'TW', 'TWN');
INSERT INTO country (name, flagcode, code) VALUES ('Tajikistan', 'TJ', 'TJK');
INSERT INTO country (name, flagcode, code) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA');
INSERT INTO country (name, flagcode, code) VALUES ('Thailand', 'TH', 'THA');
INSERT INTO country (name, flagcode, code) VALUES ('Timor-Leste', 'TL', 'TLS');
INSERT INTO country (name, flagcode, code) VALUES ('Togo', 'TG', 'TGO');
INSERT INTO country (name, flagcode, code) VALUES ('Tokelau', 'TK', 'TKL');
INSERT INTO country (name, flagcode, code) VALUES ('Tonga', 'TO', 'TON');
INSERT INTO country (name, flagcode, code) VALUES ('Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO country (name, flagcode, code) VALUES ('Tunisia', 'TN', 'TUN');
INSERT INTO country (name, flagcode, code) VALUES ('Turkey', 'TR', 'TUR');
INSERT INTO country (name, flagcode, code) VALUES ('Turkmenistan', 'TM', 'TKM');
INSERT INTO country (name, flagcode, code) VALUES ('Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO country (name, flagcode, code) VALUES ('Tuvalu', 'TV', 'TUV');
INSERT INTO country (name, flagcode, code) VALUES ('Uganda', 'UG', 'UGA');
INSERT INTO country (name, flagcode, code) VALUES ('Ukraine', 'UA', 'UKR');
INSERT INTO country (name, flagcode, code) VALUES ('United Arab Emirates', 'AE', 'ARE');
INSERT INTO country (name, flagcode, code) VALUES ('United Kingdom', 'GB', 'GBR');
INSERT INTO country (name, flagcode, code) VALUES ('United States', 'US', 'USA');
INSERT INTO country (name, flagcode, code) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI');
INSERT INTO country (name, flagcode, code) VALUES ('Uruguay', 'UY', 'URY');
INSERT INTO country (name, flagcode, code) VALUES ('Uzbekistan', 'UZ', 'UZB');
INSERT INTO country (name, flagcode, code) VALUES ('Vanuatu', 'VU', 'VUT');
INSERT INTO country (name, flagcode, code) VALUES ('Venezuela', 'VE', 'VEN');
INSERT INTO country (name, flagcode, code) VALUES ('Vietnam', 'VN', 'VNM');
INSERT INTO country (name, flagcode, code) VALUES ('British Virgin Islands', 'VG', 'VGB');
INSERT INTO country (name, flagcode, code) VALUES ('U.S. Virgin Islands', 'VI', 'VIR');
INSERT INTO country (name, flagcode, code) VALUES ('Wallis and Futuna', 'WF', 'WLF');
INSERT INTO country (name, flagcode, code) VALUES ('Western Sahara', 'EH', 'ESH');
INSERT INTO country (name, flagcode, code) VALUES ('Yemen', 'YE', 'YEM');
INSERT INTO country (name, flagcode, code) VALUES ('Zambia', 'ZM', 'ZMB');
INSERT INTO country (name, flagcode, code) VALUES ('Zimbabwe', 'ZW', 'ZWE');